/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e1e3e4",
        "surface-container-high": "#e7e8e9",
        "surface-bright": "#f8f9fa",
        secondary: "#712ae2",
        "on-primary": "#ffffff",
        "on-surface": "#191c1d",
        "surface-container-low": "#f3f4f5",
        "surface-container-highest": "#e1e3e4",
        "primary-fixed": "#e2dfff",
        error: "#ba1a1a",
        surface: "#f8f9fa",
        outline: "#777587",
        "secondary-fixed": "#eaddff",
        background: "#f8f9fa",
        "surface-container": "#edeeef",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "secondary-container": "#8a4cfc",
        "on-surface-variant": "#464555",
        "on-background": "#191c1d",
        "primary-container": "#4f46e5",
        "inverse-surface": "#2e3132",
        primary: "#3525cd",
        "surface-tint": "#4d44e3",
        "outline-variant": "#c7c4d8",
      },
      borderRadius: {
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.5rem",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "2xl": "48px",
        "container-margin": "20px",
        gutter: "16px",
      },
      fontFamily: {
        "display-word": ["Inter", "sans-serif"],
        "headline-lg": ["Be Vietnam Pro", "sans-serif"],
        "headline-md": ["Be Vietnam Pro", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "translation-text": ["Be Vietnam Pro", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-word": ["48px", { lineHeight: "56px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px" }],
        "body-md": ["16px", { lineHeight: "24px" }],
        "translation-text": ["20px", { lineHeight: "30px", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      boxShadow: {
        "level-1": "0 4px 12px rgba(0, 0, 0, 0.03)",
        "level-2": "0 8px 24px rgba(79, 70, 229, 0.1)",
      },
    },
  },
  plugins: [],
};
