export const SETS = [];
function set(topic, words) { SETS.push({ topic, words }); }

set("Education & Pedagogy", [
  ["rote memorisation", "/rəʊt ˌmeməraɪˈzeɪʃən/", "học thuộc lòng máy móc", "learning by repetition without understanding", "Rote memorisation rarely produces deep understanding.", "Học thuộc lòng máy móc hiếm khi tạo ra sự hiểu biết sâu sắc.", "noun phrase", "C1"],
  ["differentiated instruction", "/ˌdɪfəˈrenʃieɪtɪd ɪnˈstrʌkʃən/", "dạy học phân hóa", "tailoring teaching to individual student needs", "Differentiated instruction helps mixed-ability classes thrive.", "Dạy học phân hóa giúp các lớp có trình độ khác nhau phát triển tốt.", "noun phrase", "C2"],
  ["truancy", "/ˈtruːənsi/", "trốn học", "the act of staying away from school without permission", "The school introduced measures to reduce truancy.", "Nhà trường đưa ra các biện pháp giảm tình trạng trốn học.", "noun", "C1"],
  ["streaming", "/ˈstriːmɪŋ/", "phân lớp theo năng lực", "grouping pupils by ability level", "Streaming students by ability remains a contentious policy.", "Phân lớp học sinh theo năng lực vẫn là chính sách gây tranh cãi.", "noun", "C2"],
  ["extracurricular", "/ˌekstrəkəˈrɪkjələ/", "ngoại khóa", "outside the regular course of study", "Extracurricular activities develop skills exams cannot measure.", "Hoạt động ngoại khóa phát triển những kỹ năng mà bài thi không đo được.", "adjective", "C1"],
  ["formative assessment", "/ˈfɔːmətɪv əˈsesmənt/", "đánh giá quá trình", "ongoing evaluation used to guide learning", "Formative assessment lets teachers adjust lessons in real time.", "Đánh giá quá trình cho phép giáo viên điều chỉnh bài giảng ngay lập tức.", "noun phrase", "C2"],
  ["autonomy in learning", "/ɔːˈtɒnəmi ɪn ˈlɜːnɪŋ/", "tự chủ trong học tập", "students taking responsibility for their own study", "Autonomy in learning prepares students for university.", "Tự chủ trong học tập chuẩn bị cho sinh viên bước vào đại học.", "noun phrase", "C2"],
  ["remedial class", "/rɪˈmiːdiəl klɑːs/", "lớp phụ đạo", "a class for students needing extra help", "Struggling pupils were placed in a remedial class.", "Học sinh yếu được xếp vào lớp phụ đạo.", "noun phrase", "C1"],
  ["curricular reform", "/kəˈrɪkjələ rɪˈfɔːm/", "cải cách chương trình học", "changes made to what and how subjects are taught", "Curricular reform introduced coding into primary schools.", "Cải cách chương trình học đã đưa lập trình vào tiểu học.", "noun phrase", "C2"],
  ["cramming", "/ˈkræmɪŋ/", "học nhồi nhét", "studying intensively just before an exam", "Cramming the night before rarely leads to lasting knowledge.", "Học nhồi nhét đêm trước hiếm khi tạo ra kiến thức bền vững.", "noun", "C1"],
  ["dropout rate", "/ˈdrɒpaʊt reɪt/", "tỷ lệ bỏ học", "the proportion of students who leave before finishing", "The dropout rate fell after free meals were introduced.", "Tỷ lệ bỏ học giảm sau khi triển khai bữa ăn miễn phí.", "noun phrase", "B2"],
  ["peer learning", "/pɪə ˈlɜːnɪŋ/", "học tập từ bạn bè", "students learning from and with each other", "Peer learning encourages students to explain concepts aloud.", "Học tập từ bạn bè khuyến khích học sinh giải thích khái niệm thành lời.", "noun phrase", "C1"],
  ["academic rigour", "/ˌækəˈdemɪk ˈrɪɡə/", "tính học thuật nghiêm ngặt", "high intellectual standards in study", "The programme is known for its academic rigour.", "Chương trình nổi tiếng với tính học thuật nghiêm ngặt.", "noun phrase", "C2"],
  ["distance learning", "/ˈdɪstəns ˈlɜːnɪŋ/", "học từ xa", "studying remotely rather than in a classroom", "Distance learning opened universities to rural students.", "Học từ xa đã mở cửa đại học cho sinh viên nông thôn.", "noun phrase", "B2"],
  ["holistic education", "/həʊˈlɪstɪk ˌedjuˈkeɪʃən/", "giáo dục toàn diện", "education addressing intellectual, emotional and social growth", "Holistic education values character as much as grades.", "Giáo dục toàn diện coi trọng nhân cách ngang với điểm số.", "noun phrase", "C2"],
  ["standardised testing", "/ˈstændədaɪzd ˈtestɪŋ/", "thi chuẩn hóa", "uniform exams taken by all students", "Critics argue standardised testing narrows the curriculum.", "Các nhà phê bình cho rằng thi chuẩn hóa thu hẹp chương trình học.", "noun phrase", "C1"],
  ["mentor", "/ˈmentɔː/", "người cố vấn", "an experienced person who advises a less experienced one", "A good mentor can shape a student's entire career.", "Một người cố vấn tốt có thể định hình cả sự nghiệp của học sinh.", "noun", "B2"],
  ["conducive to learning", "/kənˈdjuːsɪv tə ˈlɜːnɪŋ/", "thuận lợi cho việc học", "creating conditions that help study", "A quiet, well-lit room is conducive to learning.", "Một căn phòng yên tĩnh, đủ sáng thuận lợi cho việc học.", "adjective phrase", "C2"],
  ["plagiarism", "/ˈpleɪdʒərɪzəm/", "đạo văn", "using someone else's work as one's own", "The university has strict penalties for plagiarism.", "Trường đại học có hình phạt nghiêm khắc cho việc đạo văn.", "noun", "C1"],
  ["lifelong learning", "/ˌlaɪflɒŋ ˈlɜːnɪŋ/", "học tập suốt đời", "continuing to study throughout one's life", "Lifelong learning is essential in a fast-changing job market.", "Học tập suốt đời là điều thiết yếu trong thị trường việc làm thay đổi nhanh.", "noun phrase", "B2"],
]);

set("Language & Linguistics", [
  ["etymology", "/ˌetɪˈmɒlədʒi/", "từ nguyên học", "the study of the origin of words", "The etymology of the word traces back to Latin.", "Từ nguyên của từ này bắt nguồn từ tiếng Latin.", "noun", "C2"],
  ["bilingualism", "/baɪˈlɪŋɡwəlɪzəm/", "song ngữ", "the ability to speak two languages fluently", "Bilingualism has been linked to cognitive advantages.", "Song ngữ được cho là mang lại lợi thế về nhận thức.", "noun", "C1"],
  ["colloquial", "/kəˈləʊkwiəl/", "thông tục, khẩu ngữ", "used in ordinary conversation rather than formal speech", "The essay was rejected for its colloquial tone.", "Bài luận bị từ chối vì giọng văn quá thông tục.", "adjective", "C1"],
  ["fluency", "/ˈfluːənsi/", "sự trôi chảy", "the ability to speak smoothly and easily", "Daily practice is the fastest route to fluency.", "Luyện tập hàng ngày là con đường nhanh nhất đến sự trôi chảy.", "noun", "B2"],
  ["idiomatic", "/ˌɪdiəˈmætɪk/", "mang tính thành ngữ", "using expressions natural to a native speaker", "Her writing is grammatically correct but rarely idiomatic.", "Bài viết của cô đúng ngữ pháp nhưng hiếm khi mang tính thành ngữ.", "adjective", "C1"],
  ["phonetics", "/fəˈnetɪks/", "ngữ âm học", "the study of speech sounds", "Phonetics helps learners pronounce unfamiliar words.", "Ngữ âm học giúp người học phát âm những từ lạ.", "noun", "C1"],
  ["lexicon", "/ˈleksɪkən/", "vốn từ vựng", "the vocabulary of a person or language", "Reading widely expands a learner's lexicon.", "Đọc rộng mở rộng vốn từ vựng của người học.", "noun", "C2"],
  ["morphology", "/mɔːˈfɒlədʒi/", "hình thái học (từ)", "the study of word structure and formation", "English morphology relies heavily on prefixes and suffixes.", "Hình thái học tiếng Anh phụ thuộc nhiều vào tiền tố và hậu tố.", "noun", "C2"],
  ["intonation", "/ˌɪntəˈneɪʃən/", "ngữ điệu", "the rise and fall of the voice in speech", "Rising intonation often signals a question.", "Ngữ điệu lên thường báo hiệu một câu hỏi.", "noun", "C1"],
  ["language attrition", "/ˈlæŋɡwɪdʒ əˈtrɪʃən/", "sự mai một ngôn ngữ", "the gradual loss of a language by a speaker", "Language attrition is common among second-generation migrants.", "Sự mai một ngôn ngữ phổ biến ở người di cư thế hệ thứ hai.", "noun phrase", "C2"],
  ["semantics", "/sɪˈmæntɪks/", "ngữ nghĩa học", "the study of meaning in language", "The disagreement was really about semantics.", "Sự bất đồng thực ra chỉ là về ngữ nghĩa.", "noun", "C1"],
  ["vernacular", "/vəˈnækjələ/", "tiếng địa phương, thổ ngữ", "the everyday language of a particular region", "The poet wrote deliberately in the local vernacular.", "Nhà thơ cố ý viết bằng thổ ngữ địa phương.", "noun", "C2"],
  ["articulate", "/ɑːˈtɪkjələt/", "diễn đạt rõ ràng", "able to express ideas clearly and fluently", "She is an articulate speaker who holds an audience easily.", "Cô là diễn giả diễn đạt rõ ràng, dễ dàng thu hút khán giả.", "adjective", "C1"],
  ["loanword", "/ˈləʊnwɜːd/", "từ mượn", "a word adopted from another language", "English contains thousands of French loanwords.", "Tiếng Anh chứa hàng nghìn từ mượn từ tiếng Pháp.", "noun", "C1"],
  ["syntax", "/ˈsɪntæks/", "cú pháp", "the arrangement of words to form sentences", "Learners often transfer syntax from their first language.", "Người học thường chuyển cú pháp từ tiếng mẹ đẻ sang.", "noun", "C1"],
  ["mother tongue interference", "/ˈmʌðə tʌŋ ˌɪntəˈfɪərəns/", "ảnh hưởng tiếng mẹ đẻ", "errors caused by the influence of one's first language", "Mother tongue interference explains many pronunciation errors.", "Ảnh hưởng tiếng mẹ đẻ giải thích nhiều lỗi phát âm.", "noun phrase", "C2"],
  ["endangered language", "/ɪnˈdeɪndʒəd ˈlæŋɡwɪdʒ/", "ngôn ngữ có nguy cơ biến mất", "a language at risk of falling out of use", "Linguists are racing to record endangered languages.", "Các nhà ngôn ngữ học đang chạy đua ghi lại các ngôn ngữ có nguy cơ biến mất.", "noun phrase", "C1"],
  ["register", "/ˈredʒɪstə/", "văn phong, cấp độ ngôn ngữ", "the level of formality used in language", "Emails to a professor require a more formal register.", "Email gửi giáo sư đòi hỏi văn phong trang trọng hơn.", "noun", "C2"],
  ["code-switching", "/ˈkəʊd swɪtʃɪŋ/", "chuyển mã ngôn ngữ", "alternating between two languages in conversation", "Code-switching is normal in bilingual households.", "Chuyển mã ngôn ngữ là điều bình thường trong gia đình song ngữ.", "noun", "C2"],
  ["paraphrase", "/ˈpærəfreɪz/", "diễn giải lại", "to express the same meaning in different words", "Candidates are expected to paraphrase the question in their answer.", "Thí sinh được kỳ vọng diễn giải lại câu hỏi trong câu trả lời.", "verb", "B2"],
]);

set("Art & Architecture", [
  ["minimalist", "/ˈmɪnɪməlɪst/", "tối giản", "using very simple forms and few elements", "The gallery favours a minimalist style of display.", "Phòng trưng bày ưa chuộng phong cách trưng bày tối giản.", "adjective", "C1"],
  ["mural", "/ˈmjʊərəl/", "tranh tường", "a large painting done directly on a wall", "A community mural now covers the side of the building.", "Một bức tranh tường cộng đồng hiện phủ kín mặt bên tòa nhà.", "noun", "B2"],
  ["symmetry", "/ˈsɪmətri/", "tính đối xứng", "balanced proportions between two halves", "Classical architecture prizes symmetry above all.", "Kiến trúc cổ điển đề cao tính đối xứng hơn hết.", "noun", "B2"],
  ["ornate", "/ɔːˈneɪt/", "cầu kỳ, hoa mỹ", "elaborately decorated", "The cathedral's ornate ceiling took decades to complete.", "Trần nhà thờ cầu kỳ mất hàng thập kỷ để hoàn thành.", "adjective", "C1"],
  ["restoration", "/ˌrestəˈreɪʃən/", "sự phục chế", "returning something to its original condition", "The restoration of the fresco revealed its original colours.", "Việc phục chế bức bích họa đã làm lộ ra màu sắc nguyên bản.", "noun", "C1"],
  ["avant-garde", "/ˌævɒŋ ˈɡɑːd/", "tiên phong (nghệ thuật)", "radically new and experimental in style", "Her avant-garde sculptures divided critics.", "Các tác phẩm điêu khắc tiên phong của cô chia rẽ giới phê bình.", "adjective", "C2"],
  ["patronage", "/ˈpætrənɪdʒ/", "sự bảo trợ", "financial support given to an artist", "Renaissance art flourished under wealthy patronage.", "Nghệ thuật Phục hưng nở rộ dưới sự bảo trợ của giới giàu có.", "noun", "C2"],
  ["perspective", "/pəˈspektɪv/", "phối cảnh", "the technique of representing depth on a flat surface", "Mastery of perspective transformed Renaissance painting.", "Việc làm chủ phối cảnh đã thay đổi hội họa Phục hưng.", "noun", "B2"],
  ["curator", "/kjʊəˈreɪtə/", "người phụ trách trưng bày", "a person who selects and manages a collection", "The curator arranged the works by theme rather than date.", "Người phụ trách sắp xếp các tác phẩm theo chủ đề thay vì thời gian.", "noun", "C1"],
  ["vernacular architecture", "/vəˈnækjələ ˈɑːkɪtektʃə/", "kiến trúc bản địa", "building styles based on local needs and materials", "Vernacular architecture adapts naturally to the climate.", "Kiến trúc bản địa thích ứng tự nhiên với khí hậu.", "noun phrase", "C2"],
  ["motif", "/məʊˈtiːf/", "họa tiết, mô-típ", "a recurring design or theme", "A floral motif runs through the entire collection.", "Một họa tiết hoa chạy xuyên suốt cả bộ sưu tập.", "noun", "C1"],
  ["load-bearing", "/ˈləʊd beərɪŋ/", "chịu lực", "supporting the weight of a structure", "The load-bearing walls cannot be removed.", "Các bức tường chịu lực không thể tháo bỏ.", "adjective", "C1"],
  ["monumental scale", "/ˌmɒnjʊˈmentl skeɪl/", "quy mô hoành tráng", "very large size, intended to impress", "The temple was built on a monumental scale.", "Ngôi đền được xây dựng ở quy mô hoành tráng.", "noun phrase", "C1"],
  ["abstraction", "/æbˈstrækʃən/", "sự trừu tượng hóa", "art that does not represent things realistically", "His later work moved towards pure abstraction.", "Tác phẩm về sau của ông chuyển sang trừu tượng thuần túy.", "noun", "C2"],
  ["colonnade", "/ˌkɒləˈneɪd/", "hàng cột", "a row of evenly spaced columns", "A shaded colonnade runs along the courtyard.", "Một hàng cột râm mát chạy dọc sân trong.", "noun", "C2"],
  ["renovate", "/ˈrenəveɪt/", "cải tạo", "to repair and improve an old building", "They renovated the warehouse into a modern studio.", "Họ cải tạo nhà kho thành một studio hiện đại.", "verb", "B2"],
  ["sustainable design", "/səˈsteɪnəbl dɪˈzaɪn/", "thiết kế bền vững", "design minimising environmental impact", "Sustainable design reduces a building's energy demand.", "Thiết kế bền vững làm giảm nhu cầu năng lượng của tòa nhà.", "noun phrase", "C1"],
  ["craftsmanship", "/ˈkrɑːftsmənʃɪp/", "tay nghề thủ công", "skill in making things by hand", "The craftsmanship of the carving is remarkable.", "Tay nghề thủ công của tác phẩm chạm khắc thật đáng chú ý.", "noun", "C1"],
  ["landmark building", "/ˈlændmɑːk ˈbɪldɪŋ/", "công trình biểu tượng", "a building recognised as an important local feature", "The opera house became a landmark building overnight.", "Nhà hát opera trở thành công trình biểu tượng chỉ sau một đêm.", "noun phrase", "B2"],
  ["evocative", "/ɪˈvɒkətɪv/", "gợi cảm xúc", "bringing strong images or feelings to mind", "The photograph is evocative of a vanished era.", "Bức ảnh gợi lên hình ảnh của một thời đại đã biến mất.", "adjective", "C2"],
]);

set("Music & Performance", [
  ["improvisation", "/ˌɪmprəvaɪˈzeɪʃən/", "sự ứng tấu", "creating music or drama spontaneously", "Jazz relies heavily on improvisation.", "Nhạc jazz phụ thuộc nhiều vào sự ứng tấu.", "noun", "C1"],
  ["repertoire", "/ˈrepətwɑː/", "tiết mục biểu diễn", "the works an artist is prepared to perform", "The orchestra's repertoire spans four centuries.", "Tiết mục của dàn nhạc trải dài bốn thế kỷ.", "noun", "C1"],
  ["virtuoso", "/ˌvɜːtʃuˈəʊzəʊ/", "nghệ sĩ bậc thầy", "a person with exceptional skill in performance", "The young violinist is already a virtuoso.", "Nghệ sĩ violin trẻ đã là một bậc thầy.", "noun", "C2"],
  ["rendition", "/renˈdɪʃən/", "phần trình bày, bản thể hiện", "a performance or interpretation of a work", "Her rendition of the song moved the audience to tears.", "Phần thể hiện ca khúc của cô khiến khán giả rơi lệ.", "noun", "C1"],
  ["choreography", "/ˌkɒriˈɒɡrəfi/", "biên đạo múa", "the arrangement of dance movements", "The choreography blends classical and street dance.", "Phần biên đạo kết hợp múa cổ điển và nhảy đường phố.", "noun", "C1"],
  ["ensemble", "/ɒnˈsɒmbl/", "nhóm hòa tấu", "a group of musicians or actors performing together", "The chamber ensemble performs every Friday.", "Nhóm hòa tấu thính phòng biểu diễn vào mỗi thứ Sáu.", "noun", "C1"],
  ["tempo", "/ˈtempəʊ/", "nhịp độ", "the speed at which music is played", "The conductor slowed the tempo in the final movement.", "Nhạc trưởng làm chậm nhịp độ ở chương cuối.", "noun", "B2"],
  ["resonate", "/ˈrezəneɪt/", "cộng hưởng, gây tiếng vang", "to produce a deep sound or a strong emotional effect", "The lyrics resonate with young listeners.", "Lời bài hát gây tiếng vang với người nghe trẻ tuổi.", "verb", "C1"],
  ["orchestration", "/ˌɔːkɪˈstreɪʃən/", "phối khí", "arranging music for an orchestra", "The film's orchestration won an award.", "Phần phối khí của bộ phim đã đoạt giải.", "noun", "C2"],
  ["debut", "/ˈdeɪbjuː/", "buổi ra mắt", "a first public appearance or performance", "She made her debut at the age of nineteen.", "Cô có buổi ra mắt năm mười chín tuổi.", "noun", "B2"],
  ["understudy", "/ˈʌndəstʌdi/", "diễn viên dự bị", "an actor who learns a role to replace the main performer", "The understudy stepped in when the lead fell ill.", "Diễn viên dự bị đã thay thế khi vai chính bị ốm.", "noun", "C2"],
  ["acclaimed", "/əˈkleɪmd/", "được ca ngợi", "praised publicly and enthusiastically", "The acclaimed production toured internationally.", "Vở diễn được ca ngợi đã lưu diễn quốc tế.", "adjective", "C1"],
  ["encore", "/ˈɒŋkɔː/", "phần diễn thêm theo yêu cầu", "an extra performance given after applause", "The band played three encores.", "Ban nhạc đã chơi thêm ba lần theo yêu cầu.", "noun", "C1"],
  ["lyrical", "/ˈlɪrɪkl/", "trữ tình", "expressing emotion in a beautiful, poetic way", "The film's lyrical soundtrack lingers long after.", "Nhạc phim trữ tình còn đọng lại rất lâu sau đó.", "adjective", "C2"],
  ["auditorium", "/ˌɔːdɪˈtɔːriəm/", "khán phòng", "the part of a theatre where the audience sits", "The auditorium seats over two thousand people.", "Khán phòng có sức chứa hơn hai nghìn người.", "noun", "B2"],
  ["stage presence", "/steɪdʒ ˈprezəns/", "phong thái sân khấu", "a performer's ability to command attention", "Her stage presence alone justified the ticket price.", "Chỉ riêng phong thái sân khấu của cô đã đáng giá vé.", "noun phrase", "C1"],
  ["dissonance", "/ˈdɪsənəns/", "sự nghịch tai", "a combination of notes that sounds harsh", "The composer used dissonance to create tension.", "Nhà soạn nhạc dùng sự nghịch tai để tạo căng thẳng.", "noun", "C2"],
  ["mainstream appeal", "/ˈmeɪnstriːm əˈpiːl/", "sức hút đại chúng", "the quality of attracting a wide general audience", "The album traded experimentation for mainstream appeal.", "Album đã đánh đổi tính thử nghiệm lấy sức hút đại chúng.", "noun phrase", "C1"],
  ["rehearsal", "/rɪˈhɜːsl/", "buổi tập dượt", "a practice session before a performance", "The final rehearsal ran until midnight.", "Buổi tập dượt cuối cùng kéo dài đến nửa đêm.", "noun", "B2"],
  ["patron of the arts", "/ˈpeɪtrən əv ðə ɑːts/", "nhà bảo trợ nghệ thuật", "a person who financially supports artists", "The businessman became a well-known patron of the arts.", "Doanh nhân này trở thành nhà bảo trợ nghệ thuật nổi tiếng.", "noun phrase", "C2"],
]);

set("Literature & Writing", [
  ["narrative arc", "/ˈnærətɪv ɑːk/", "mạch truyện", "the overall shape of a story from beginning to end", "The novel's narrative arc spans three generations.", "Mạch truyện của cuốn tiểu thuyết trải dài ba thế hệ.", "noun phrase", "C1"],
  ["protagonist", "/prəˈtæɡənɪst/", "nhân vật chính", "the leading character in a story", "The protagonist undergoes a profound transformation.", "Nhân vật chính trải qua một sự biến đổi sâu sắc.", "noun", "C1"],
  ["allegory", "/ˈæləɡəri/", "truyện ngụ ý, ẩn dụ", "a story with a hidden moral or political meaning", "The book is an allegory of political corruption.", "Cuốn sách là một truyện ngụ ý về tham nhũng chính trị.", "noun", "C2"],
  ["prose", "/prəʊz/", "văn xuôi", "ordinary written language, not poetry", "His prose is spare but powerful.", "Văn xuôi của ông giản dị nhưng mạnh mẽ.", "noun", "C1"],
  ["foreshadowing", "/fɔːˈʃædəʊɪŋ/", "sự báo trước (trong truyện)", "hinting at events that will happen later", "The storm in chapter one is clear foreshadowing.", "Cơn bão ở chương một rõ ràng là một sự báo trước.", "noun", "C2"],
  ["memoir", "/ˈmemwɑː/", "hồi ký", "an account of the author's own life", "Her memoir describes childhood in wartime.", "Hồi ký của bà mô tả tuổi thơ trong thời chiến.", "noun", "C1"],
  ["satire", "/ˈsætaɪə/", "châm biếm", "the use of humour to criticise people or ideas", "The play is a sharp satire on modern politics.", "Vở kịch là một tác phẩm châm biếm sắc bén về chính trị hiện đại.", "noun", "C1"],
  ["anthology", "/ænˈθɒlədʒi/", "tuyển tập", "a collection of works by various authors", "The anthology gathers poems from twenty countries.", "Tuyển tập tập hợp các bài thơ từ hai mươi quốc gia.", "noun", "C1"],
  ["imagery", "/ˈɪmɪdʒəri/", "hình ảnh (văn học)", "descriptive language that creates mental pictures", "The poem's imagery of water recurs throughout.", "Hình ảnh nước trong bài thơ lặp lại xuyên suốt.", "noun", "C1"],
  ["unreliable narrator", "/ˌʌnrɪˈlaɪəbl nəˈreɪtə/", "người kể chuyện không đáng tin", "a storyteller whose account cannot be fully trusted", "The twist relies on an unreliable narrator.", "Nút thắt dựa vào một người kể chuyện không đáng tin.", "noun phrase", "C2"],
  ["manuscript", "/ˈmænjəskrɪpt/", "bản thảo", "an author's text before publication", "The manuscript was rejected by twelve publishers.", "Bản thảo đã bị mười hai nhà xuất bản từ chối.", "noun", "B2"],
  ["genre", "/ˈʒɒnrə/", "thể loại", "a category of artistic work", "She writes across several genres, from crime to romance.", "Cô viết qua nhiều thể loại, từ trinh thám đến lãng mạn.", "noun", "B2"],
  ["metaphorical", "/ˌmetəˈfɒrɪkl/", "mang tính ẩn dụ", "using figurative rather than literal language", "The title is metaphorical rather than descriptive.", "Tựa đề mang tính ẩn dụ hơn là mô tả.", "adjective", "C1"],
  ["compelling", "/kəmˈpelɪŋ/", "cuốn hút", "holding attention powerfully", "The opening chapter is utterly compelling.", "Chương mở đầu vô cùng cuốn hút.", "adjective", "C1"],
  ["excerpt", "/ˈeksɜːpt/", "đoạn trích", "a short passage taken from a longer text", "The magazine published an excerpt from the new novel.", "Tạp chí đã đăng một đoạn trích từ cuốn tiểu thuyết mới.", "noun", "B2"],
  ["poignant", "/ˈpɔɪnjənt/", "day dứt, xúc động sâu sắc", "evoking a keen sense of sadness", "The final scene is quietly poignant.", "Cảnh cuối cùng day dứt một cách lặng lẽ.", "adjective", "C2"],
  ["protracted", "/prəˈtræktɪd/", "kéo dài dai dẳng", "lasting longer than expected or necessary", "The novel suffers from a protracted middle section.", "Cuốn tiểu thuyết bị ảnh hưởng bởi phần giữa kéo dài dai dẳng.", "adjective", "C2"],
  ["verbose", "/vɜːˈbəʊs/", "dài dòng", "using more words than necessary", "The report was criticised as verbose and unclear.", "Báo cáo bị chỉ trích là dài dòng và không rõ ràng.", "adjective", "C2"],
  ["coherent argument", "/kəʊˈhɪərənt ˈɑːɡjəmənt/", "lập luận mạch lạc", "a well-organised, logically connected line of reasoning", "Examiners reward a coherent argument over fancy vocabulary.", "Giám khảo đánh giá cao lập luận mạch lạc hơn là từ vựng hoa mỹ.", "noun phrase", "C1"],
  ["concise", "/kənˈsaɪs/", "súc tích", "giving information clearly in few words", "A concise summary is more persuasive than a long one.", "Một bản tóm tắt súc tích thuyết phục hơn một bản dài dòng.", "adjective", "B2"],
]);
